apiVersion: v1
data:
    age.key: ENC[AES256_GCM,data:dEEpQhPjsSkOub6LmrhtDqTi6CJy9r2gbpT7kGcRiRlbHShq39NN27YUYZiVAuCletIz5lsHHQCQxotUfyI2pEH5U2yIbpXRuAChp32PiFrIBoa9189cENMi5EaQqN5nNY6tK8SEoUr7wzolIBbQf9q3elou5Dq1oU+SyuVgsNUZbJNKk1ACLQ8qP/kCr3OwxWCwDnz60FpcOZkNAQPkmOm4ccWq+9caInoNunKMwDa3FYYbAGeBNbzDdr9FT6V1IJvzaVMQ4Ft66N3sJ8JzJjUP2ioz6u1mciKStBicYWpLUvXLX3cj5s2tb7YxR62GRtZga5ixC1hU8U45,iv:3YogSzviNbsb/U9D35YvM+VsLYZAXEEsThQConbU8yc=,tag:uqMWTcgj7BIC5IQTwGz62w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sops-age
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12dz8cp24rpc5mw7kjzzsm473k2hupgfgne7mkp976nf90lke54qsv2utn0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNEpNVXY1UHMwSHdEMXox
            dmFJUVg4THRFM2R1bzdjVmZXU0d0T0xGRVZBCmp2dms5U2ZCMHJkb0huZXgybkdu
            ZEd5V045dU5MejFEQ2N2cEMyRUltdncKLS0tIEVYZGlWdk03U1FiaWgwalZ0UWxH
            eGVUR3l4MVZEOThBRFE2Vkx5QVN1bnMKey0aIAmyL/J4Hafqr1AI4LulVpRGXwam
            m2sce/0fxVf8tHpYwmqxX414YzlB1hbu5tt3WAPDuXNJ1pMUTT9r3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T02:56:15Z"
    mac: ENC[AES256_GCM,data:ChJPIQ4d5TPf8rq8Y3mUMzhXjTdw7723o/SJPCvyEtfJxr59AjjnH+9G3E2KPRURrej5AUvTjR0RtCQ5zqUGuPukFURyalulisVrVEgVYJqf5HtHxM5pVnuiSgN+U4QtrA02R0cjkIcW8UbwqYnAdkqN6sFDE07ZJ2Rp/3P/H60=,iv:w1DGCAXZ114FwsC8cQa1/a9JXu3J4rmjANZEqMZqAgU=,tag:esyUmhE9OBgZOYSKvz6osw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
