apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:kVx8sy66qZwW2l678qluylxKwUHjSHP2zbVq6X7czVQuPdxEehGjGo0JFhMxYiHw1WUG37ZgoI7ecNfECx3N1SJynPkwtMfHLMNaxZBZl1w7jTRrMmnGrntuxbhAClo48rY3/A0YAfAzGBNK9/eJ56Xvhf+tFKqSzPLomYSbjGkWJ5ZFWyiNodIPpJfRySVL/E4T6HYkhZK9xWPzthtqxijhFRlj8Vo1A+ARcbrl/4w7JpAMUS/kNhubKfI//WxmKgnPi1bsRgM8n7l4BJssQ+hcZsvE6gdM7dvbW4kW4gWO92PZk9rmwA0i+aY=,iv:puGWuRYzXr9rj9nztN2yKcxt3CWt81ll2hpNAKUIOus=,tag:lLju/lJPhnxYhhCOBR097A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12dz8cp24rpc5mw7kjzzsm473k2hupgfgne7mkp976nf90lke54qsv2utn0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNWdEK0hGMGQ5MjN5OVZa
            TkZTaWppOXFJQnlMSksrS0tLZGR0UWFyOXlVCmlNSVBCZ05pRTlRMGgwSE5XS1dx
            TE83QWl5LzkzSFAxUWcvTHVpVm1xeUUKLS0tIE9iMjZ3RG85WWR4bGw1czUvYUo3
            ekNpL1ZVZkJ4VTU2YVRYamZTR1NqNUUK/BXaXbWyALeHut6SxWIcps5eNtgaqpI7
            KzaTOYgkRG6VVD8a5IuGhZfv6+tpXKR3J0VyRJLH4o/4a0b2cSwkCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T20:11:18Z"
    mac: ENC[AES256_GCM,data:uSVV0Wy2i3U0R/gCUw/IzkBUp6uvOXJBaUiMcBYj+CvAlc4EXLR0CFtB/SOEh6/RGH5reE/Oxn+4xY9hrnWzwyFZ6C7YTvmaj7A/eZ2QPmmvhCWkloZ0tBW+1BQokrUy1I7sQjVLRT9PXRfMyyY9ex52S+3qYlL+/43OkkJnUW4=,iv:v2LqSfkw6o8wp2s5Pnf3kksFhJiPFQbyndrU7K7BF+k=,tag:g5PuyjqSgOrEGeNQSredEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
