apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:kQshlSpFpreno9I+aP9oOPV5saBu0CDlF3vIiuQ5Qkm/Q/DDpCGw6cKR+G8r7KbaRgsLMW376K4=,iv:n6NS0d7SPRLp1kieph6zHyT5kHDVL9M/62Cmrbt9Cgk=,tag:JNWjTLLSjDksz2B+wTi41A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-container-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12dz8cp24rpc5mw7kjzzsm473k2hupgfgne7mkp976nf90lke54qsv2utn0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOUN4UER5elNzWHY3S0o0
            ZklHNmJMK1pvT2N5K0FlR2xUdkVrRkQwTm1rClY0a1pwa09WZkR4d2tkY3Y1Y28r
            K2VkV0k4T0xpWnBtZ0dWN3QrTzNScGsKLS0tIExkRWZTNVVhZHFoR3o4WGpiVk5y
            d2dlVysvSWgwNm9NTEFsWWk4VFJxdkkK9Ym7VFn/C2OgNRnijQNss9Hex5Q7d297
            e6CBNmLQrsm06DS2002p9zHAGyIZ6pPQXhZLSNQ/+SlDvBY7tZRDGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T18:54:12Z"
    mac: ENC[AES256_GCM,data:Q5Diwlo6MUh1LxZUDQyijU5eZCc764b7F8vImHWji+tGwcIad6xFzBCugxBAwFQbHku2X5cDf8zERUx4sEIjPoqYRsX1sL5teOGiGWdY8u5GUXDVm/HL00uH0B0cq7fOt9Z5m/1dLem70WhWrXt+Ns1jZsvQKJCDXmhTKisH7q4=,iv:aBhzPsR068lmc5so7Y9hLUUG9Fy6TWr5QKAqcmQbJz0=,tag:vaTbNthfg2ZdQ+G+eh+yxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
